apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hep-energy
resources:
  - namespace.yaml
  - pvc.yaml
  - secret.yaml        # kreiraj iz secret.example.yaml (nije u gitu)
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/bignjato/hep_ha
    newTag: latest
